# -*- coding: utf-8 -*-
"""evvehicles.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14ceglX4-K4pFKQcUpVqZF17zSecrumgb
"""

import matplotlib.pyplot as plt

plt.figure(figsize=(6,2))

plt.text(0.5,0.6,"Sowndarya Sree T",
         ha="center",
         fontsize=18)

plt.text(0.5,0.4,"727624BAM052",
         ha="center",
         fontsize=14)

plt.axis("off")
plt.show()

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("/content/ev_fleet_dataset_v15.csv")

df.head()

df.shape

df.info()

df.describe()

df.isnull().sum()

running = df[df["vehicle_status"] == "Running"]

print("Vehicles Running =", len(running))

Charging = df[df["vehicle_status"] == "Charging"]

print("Vehicles Charging =", len(Charging))

Garage = df[df["vehicle_status"] == "Garage"]

print("Vehicles Garage =", len(Garage))

Maintenance = df[df["vehicle_status"] == "Maintenance"]

print("Vehicles Maintenance =", len(Maintenance))

count = df.groupby("manufacturer")["vehicle_id"].count()

print(count)

charging = df[df["battery_percentage"] < 20]

print("Vehicles Need Charging =", len(charging))

cost = df.groupby("manufacturer")["maintenance_cost"].sum()

print(cost)

vehicle_cost = df.groupby("vehicle_id")["maintenance_cost"].sum()

print(vehicle_cost.head(20))

driver = df.groupby("driver_name")["driver_revenue"].sum()

print("Driver Name :", driver.idxmax())
print("Revenue :", f"{driver.max():,.0f}")

loss = df.groupby("driver_name")["maintenance_cost"].sum()

print("Driver Name :", loss.idxmax())
print("Loss :", f"{loss.max():,.0f}")

v = df[df["violations"] != "None"]

result = v.groupby("driver_name").size()

print("Driver Name :", result.idxmax())
print("Violations :", result.max())

df["date"] = pd.to_datetime(df["date"], dayfirst=True)

df["month"] = df["date"].dt.month_name()

month_revenue = df.groupby("month")["monthly_revenue_generation"].sum()

for month, revenue in month_revenue.items():
    print(month, ":", f"{revenue:,.0f}")